/// Central measure table containing all DAX calculations for the PostHog CRM Analytics semantic model. Includes user activity metrics (DAU, WAU, MAU), application version adoption tracking, deployment analytics, and engagement metrics. All report visuals should reference measures from this table rather than aggregating raw columns directly.
table _Measures
	lineageTag: b1b6ec74-ea38-47f5-8bbf-8980fa338115

	/// The number of unique users who generated at least one CRM activity event on the previous calendar day. Always reflects yesterday's complete data regardless of report filters. Displayed as the DAU KPI card on the Overview dashboard.
	measure 'Daily Active Users' =
			VAR _RefDate = [Reference Date]
			RETURN
			CALCULATE(
			    DISTINCTCOUNT('PostHog Application Usage Events'[User Identifier]),
			    'Calendar'[Date] = _RefDate
			)
		formatString: 0
		displayFolder: Overview Dashboard
		lineageTag: f1b089a4-eec4-4039-a738-51fe65b2f521

	/// The number of unique users who generated at least one CRM activity event during the 7 complete days prior to the most recent data date. Always reflects the trailing 7-day window ending on yesterday's date to ensure only full days are counted. Displayed as the WAU KPI card on the Overview dashboard.
	measure 'Weekly Active Users' =
			VAR _RefDate = [Reference Date]
			RETURN
			CALCULATE(
			    DISTINCTCOUNT('PostHog Application Usage Events'[User Identifier]),
			    DATESINPERIOD('Calendar'[Date], _RefDate, -7, DAY)
			)
		formatString: 0
		displayFolder: Overview Dashboard
		lineageTag: 5ae0f9fc-1ca4-4cfd-b27e-51f1dbcc97bc

		annotation PBI_FormatHint = {"isDecimal":true}

	/// The number of unique users who generated at least one CRM activity event during the 30 complete days prior to the most recent data date. Always reflects the trailing 30-day window ending on yesterday's date to ensure only full days are counted. Displayed as the MAU KPI card on the Overview dashboard.
	measure 'Monthly Active Users' =
			VAR _RefDate = [Reference Date]
			RETURN
			CALCULATE(
			    DISTINCTCOUNT('PostHog Application Usage Events'[User Identifier]),
			    DATESINPERIOD('Calendar'[Date], _RefDate, -30, DAY)
			)
		formatString: 0
		displayFolder: Overview Dashboard
		lineageTag: 3e00b356-8106-4543-a199-b4dc68a7ea9a

	/// WAU / MAU ratio. Shows what proportion of monthly users return at least once per week. Measures habitual engagement with the CRM. Benchmark for B2B CRM: 80%+ excellent, 60-80% healthy, below 40% critical.
	measure 'Stickiness WAU/MAU' = DIVIDE([Weekly Active Users], [Monthly Active Users], 0)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Overview Dashboard
		lineageTag: d749663f-bb1d-47d5-8da0-2e4dcebd453e

	/// Description
	/// "Counts the number of unique users who generated at least one activity event within the selected date range and filter context. Based on User Identifier, which ensures maximum user coverage by combining User ID, User Email, and PostHog Distinct ID. Use as the primary user count metric across all adoption and engagement reports."
	/// Business Logic
	/// Applies DISTINCTCOUNT on User Identifier. Each unique value in User Identifier represents one attributable user regardless of identification method used.
	/// Usage
	/// Use for user adoption tracking, active user reporting, and as the base metric for DAU, WAU, and MAU calculations. Always apply a date filter to avoid unintentional all-time counts.
	measure 'Active Users' =
			
			DISTINCTCOUNT('PostHog Application Usage Events'[User Identifier])
		formatString: 0
		displayFolder: Overview Dashboard
		lineageTag: 24f7040d-aa6a-47ea-b156-287c8617e159

	/// Description:
	/// Returns the current production version of the CRM mobile or web application based on the platform selected in the report slicer. For Mobile, returns the latest Flutter.Mobile version from the CRM Application Deployments table. For Web, returns the latest Flutter.Web version from the same table. This measure requires a single platform selection (Mobile or Web) — the report slicer is configured for single-select only. Use this measure as the reference version for version adoption analysis, including Current Version Adoption % and Users on Current Application Version.
	/// 
	/// Business Logic:
	/// Reads the selected Platform filter value and looks up the corresponding application version from CRM Application Deployments table by matching Flutter.Mobile or Flutter.Web application name. Returns BLANK if no single platform is selected.
	/// 
	/// Usage:
	/// Use in combination with a Platform slicer. This measure serves as the reference point for Current Version Adoption % and Users on Current Application Version measures. Always requires a single platform selection to return a meaningful value.
	measure 'Current Application Version' =
			
			VAR SelectedPlatform =
			    SELECTEDVALUE('PostHog Application Usage Events'[Platform])
			RETURN
			SWITCH(
			    TRUE(),
			
			    SelectedPlatform = "Mobile",
			        CALCULATE(
			            SELECTEDVALUE('CRM Application Deployments'[Application Version]),
			            'CRM Application Deployments'[Application Name] = "Flutter.Mobile"
			        ),
			
			    SelectedPlatform = "Web",
			        CALCULATE(
			            SELECTEDVALUE('CRM Application Deployments'[Application Version]),
			            'CRM Application Deployments'[Application Name] = "Flutter.Web"
			        ),
			
			    BLANK()
			)
		displayFolder: Application Version Adoption
		lineageTag: 4bbad64b-3e5a-4654-9898-7c320db7aca4

	/// Description:
	/// Counts the number of unique users who are running an outdated version of the CRM application for the selected platform. Calculated as the difference between Active Users and Users on Current Application Version. Requires a single platform selection via the Platform slicer — the report is configured for single-select only. Use this measure to identify the scale of users who have not yet updated to the latest production release.
	/// 
	/// Business Logic:
	/// Subtracts Users on Current Application Version from Active Users within the current filter context. Inherits platform filtering from both component measures. Returns the count of users whose application version does not match the current production deployment for the selected platform.
	/// 
	/// Usage:
	/// Use on the App Version Adoption report page in combination with the Platform slicer. A high value indicates a significant portion of users are on outdated versions and may require targeted update campaigns. Use alongside Legacy Version Adoption % for percentage-based reporting.
	/// 
	measure 'Users on Current Application Version' =
			
			VAR CurrentVersion =
			    [Current Application Version]
			VAR PlatformSelected =
			    SELECTEDVALUE('PostHog Application Usage Events'[Platform])
			VAR Result =
			    SWITCH(
			        TRUE(),
			        PlatformSelected = "Mobile",
			            CALCULATE(
			                DISTINCTCOUNT('PostHog Application Usage Events'[User Identifier]),
			                'PostHog Application Usage Events'[Application Version (Mobile)] = CurrentVersion
			            ),
			        PlatformSelected = "Web",
			            CALCULATE(
			                DISTINCTCOUNT('PostHog Application Usage Events'[User Identifier]),
			                FILTER(
			                    'PostHog Application Usage Events',
			                    RELATED('Web App Deployments'[Application Version])
			                        = CurrentVersion
			                )
			            )
			    )
			RETURN
			    COALESCE(Result, 0)
		formatString: 0
		displayFolder: Application Version Adoption
		lineageTag: 384d1c83-908f-4a3b-8a71-48396d159e62

	/// Returns the percentage of active users running the current production application version for the selected platform.
	/// 
	/// Business meaning:
	/// Measures adoption of the latest released application version and indicates how successfully users have migrated to the current production release.
	/// 
	/// Calculation:
	/// Users on Current App Version ÷ Total Active Users
	/// 
	/// Logic:
	/// - Mobile adoption is calculated using application versions captured in activity events.
	/// - Web adoption is calculated using instance-to-version mappings stored in the Web Flutter version table.
	/// 
	/// Usage:
	/// Used to monitor release rollout progress, identify upgrade gaps, and track migration from legacy versions to the current production version.
	/// 
	/// Source:
	/// Users on Current App Version
	/// Total Active Users
	/// 
	/// Notes:
	/// The measure dynamically adapts to the selected platform and respects all report filters.
	measure 'Current Version Adoption %' =
			
			DIVIDE(
			    [Users on Current Application Version],
			    [Active Users],
			    0
			)
		formatString: 0%;-0%;0%
		displayFolder: Application Version Adoption
		lineageTag: 73a62801-0635-4c16-b8e7-513dc3acf5a3

	/// Returns the number of unique active users running a version older than the current production application version.
	/// 
	/// Business meaning:
	/// Measures the population of users who have not yet migrated to the latest release.
	/// 
	/// Logic:
	/// Identifies active users whose application version differs from the current production version for the selected platform.
	/// 
	/// Usage:
	/// Used to monitor upgrade gaps, legacy version exposure, and release rollout progress.
	measure 'Users on Legacy Version' =
			
			[Active Users] - [Users on Current Application Version]
		formatString: 0
		displayFolder: Application Version Adoption
		lineageTag: b7519c18-5187-4f0c-b626-4f440c9f40df

	/// Returns the percentage of active users running a version older than the current production application version.
	/// 
	/// Business meaning:
	/// Measures the share of users remaining on legacy versions and indicates the remaining upgrade effort.
	/// 
	/// Calculation:
	/// Users on Legacy Version ÷ Total Active Users
	/// 
	/// Usage:
	/// Used to track migration progress, identify upgrade risks, and monitor release adoption across the user base.
	measure 'Legacy Version Adoption %' =
			
			1 - [Current Version Adoption %]
		displayFolder: Application Version Adoption
		lineageTag: 35bed2ac-f3fd-49ba-9da2-dff4d0f394c9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Counts the number of unique CRM client instances that generated at least one user activity event within the selected date range and filter context. Each instance represents a separate client CRM deployment or hosted environment. Use this measure to monitor how many client deployments are actively used within a given period.
	/// Business Logic
	/// Applies DISTINCTCOUNT on CRM Instance Name across all filtered PostHog events. Reacts to all filter context including date, country, platform, and other slicers.
	/// Usage
	/// Use for deployment monitoring and client activity tracking. Combine with date filters to identify active versus inactive client instances over specific periods.
	measure 'Active Instances' =
			
			DISTINCTCOUNT('PostHog Application Usage Events'[CRM Instance Name])
		formatString: 0
		displayFolder: Deployment Analytics
		lineageTag: d3ef0430-ea44-42d2-ab9b-04e2a6e56927

	/// Description:
	/// 
	/// Counts the number of unique CRM services that were actively used by at least one user within the selected date range and filter context. Use this measure to monitor service engagement breadth and identify which services are being utilized across the selected period.
	/// Business Logic:
	/// 
	/// Applies DISTINCTCOUNT on CRM Service Name across all filtered PostHog events. Reacts to all filter context including date, platform, country, instance, and user role filters. Each distinct value represents a separate CRM service such as Cloud CRM, GeoForce, Cycle Plan, or Admin Tool.
	/// Usage:
	/// 
	/// Use as a KPI card on the CRM Services page to understand how many services are actively engaged within the selected period. A low number may indicate that users are concentrated in a limited set of services. Compare across time periods to monitor service adoption growth.
	measure 'Active Services' =
			
			DISTINCTCOUNT(
			    'PostHog Application Usage Events'[CRM Service Name]
			)
		formatString: 0
		displayFolder: CRM Analytics
		lineageTag: a8a18bfb-3ea6-494d-a8ce-0b11f298ba8e

	/// Description:
	/// 
	/// Returns a formatted date range string based on the currently selected date filter from the Calendar table. Always reflects the slicer selection regardless of data availability in the fact table.
	/// Business Logic:
	/// 
	/// Uses MIN and MAX of Calendar Date within the current filter context. Since it references the Calendar table rather than event data, it consistently returns the full selected date range even when some dimensions have no activity in that period.
	/// Usage:
	/// 
	/// Use as a dynamic subtitle or title in all report visuals to display the selected reporting period consistently across all charts. Apply via conditional formatting on the visual title using Field value → Subtitle Period.
	measure 'Subtitle Period' = ```
			
			VAR _MinDate = 
			    CALCULATE(
			        MIN('Calendar'[Date]),
			        ALLSELECTED('Calendar')
			    )
			VAR _MaxDate = 
			    CALCULATE(
			        MAX('Calendar'[Date]),
			        ALLSELECTED('Calendar')
			    )
			RETURN
			"Period: " 
			& FORMAT(_MinDate, "dd.MM.yyyy")
			& " - "
			& FORMAT(_MaxDate, "dd.MM.yyyy")
			```
		displayFolder: Report Helpers
		lineageTag: c16bb7fa-564b-41ed-85c7-d4fe79e830af

	/// Description:
	/// Returns a formatted date range string representing the last 7 complete days based on the most recent date in the Calendar table. Always reflects the trailing 7-day window ending on yesterday regardless of any date slicer selection. Use as a dynamic subtitle on App Version Adoption report visuals to indicate the reporting period consistently with WAU measures.
	measure 'Subtitle Period Last 7 Days' =
			VAR _RefDate = CALCULATE ( [Reference Date], REMOVEFILTERS ( 'PostHog Application Usage Events' ) )
			VAR _MinDate = _RefDate - 6
			RETURN
			"Period: " & FORMAT(_MinDate, "dd.MM.yyyy") & " - " & FORMAT(_RefDate, "dd.MM.yyyy")
		displayFolder: Report Helpers
		lineageTag: b8581e62-f502-4621-b12a-1fb9062b55cd

	/// Description:
	/// 
	/// Counts the number of unique CRM modules that were actively used by at least one user within the selected date range and filter context. Reflects the breadth of CRM feature adoption — a higher value indicates users are exploring and utilizing a wider range of available modules.
	/// Business Logic:
	/// 
	/// Applies DISTINCTCOUNT on CRM Module Name across all filtered PostHog events. Reacts to all filter context including date, platform, country, CRM service, instance, and user role filters. Each distinct value represents a separate CRM module such as Schedule, Contacts, Companies, or Reports.
	/// Usage:
	/// 
	/// Use as a KPI card on the CRM Services page alongside Active Services to understand how broadly CRM features are being adopted. A low number relative to total available modules may indicate that users are concentrating on a limited set of features. Compare across instances or user roles to identify engagement patterns.
	measure 'Active Modules' =
			
			DISTINCTCOUNT(
			    'PostHog Application Usage Events'[CRM Module Name]
			)
		formatString: 0
		displayFolder: CRM Analytics
		lineageTag: e0872197-457f-46d1-a32d-110b5af4fd7e

	/// Description:
	/// 
	/// Measures the average number of CRM activity events generated per unique active user within the selected date range and filter context. Reflects how intensively users interact with the CRM application — a higher value indicates deeper and more frequent engagement.
	/// Business Logic:
	/// 
	/// Divides the total sum of Event Count by Active Users within the current filter context. Uses safe division with 0 as fallback to avoid division by zero errors. Reacts to all filter context including date, platform, country, CRM service, and module filters.
	/// Usage:
	/// 
	/// Use as a KPI card on the CRM Services page to monitor user engagement intensity. Compare across time periods, platforms, or user roles to identify which segments are most actively using the CRM. A declining trend may indicate reduced engagement or usability issues.
	measure 'Avg Events per User' =
			
			DIVIDE(
			    SUM('PostHog Application Usage Events'[Event Count]),
			    [Active Users],
			    0
			)
		formatString: 0
		displayFolder: CRM Analytics
		lineageTag: 0069308e-ce98-4763-a0bd-ffe11ef890a2

	/// Description:
	/// 
	/// Counts the number of unique users who interacted with CRM modules on the previous calendar day. Use this measure in trend charts to monitor daily module engagement and identify immediate impact of training sessions or feature rollouts.
	/// Business Logic:
	/// 
	/// Applies DISTINCTCOUNT on User Identifier filtered to a 1-day window ending on yesterday. Consistent with DAU calculation pattern. Reacts to all filter context including module, service, platform, country, and instance filters.
	/// Usage:
	/// 
	/// Use in the Module Activity Trend line chart to show day-by-day engagement per module. Best for short-term analysis and post-training impact measurement. Combine with CRM Module Name legend to compare module activity daily.
	measure 'Daily Active Users by Module' =
			VAR _RefDate = [Reference Date]
			RETURN
			CALCULATE(
			    DISTINCTCOUNT('PostHog Application Usage Events'[User Identifier]),
			    DATESINPERIOD('Calendar'[Date], _RefDate, -1, DAY)
			)
		formatString: 0
		displayFolder: Module Activity
		lineageTag: ae162d06-ae19-4833-b244-7e6e2783494b

	/// Description:
	/// 
	/// Counts the number of unique users who interacted with CRM modules within the last 7 complete days. Use this measure in trend charts to monitor weekly module engagement trends and identify medium-term adoption patterns across CRM modules.
	/// Business Logic:
	/// 
	/// Applies DISTINCTCOUNT on User Identifier filtered to a rolling 7-day window ending on yesterday. Consistent with WAU calculation pattern. Reacts to all filter context including module, service, platform, country, and instance filters.
	/// Usage:
	/// 
	/// Use in the Module Activity Trend line chart to show week-over-week engagement per module. Best for medium-term analysis and tracking adoption trends after training campaigns. Combine with CRM Module Name legend to compare module activity across weeks.
	measure 'Weekly Active Users by Module' =
			VAR _RefDate = [Reference Date]
			RETURN
			CALCULATE(
			    DISTINCTCOUNT('PostHog Application Usage Events'[User Identifier]),
			    DATESINPERIOD('Calendar'[Date], _RefDate, -7, DAY)
			)
		formatString: 0
		displayFolder: Module Activity
		lineageTag: 636d9d7d-30f1-45ea-b279-75173ef85873

	/// Description:
	/// 
	/// Counts the number of unique users who interacted with CRM modules within the last 30 complete days. Use this measure in trend charts to monitor monthly module engagement trends and evaluate long-term feature adoption across CRM modules.
	/// Business Logic:
	/// 
	/// Applies DISTINCTCOUNT on User Identifier filtered to a rolling 30-day window ending on yesterday. Consistent with MAU calculation pattern. Reacts to all filter context including module, service, platform, country, and instance filters.
	/// Usage:
	/// 
	/// Use in the Module Activity Trend line chart to show month-over-month engagement per module. Best for long-term adoption analysis and strategic planning. Combine with CRM Module Name legend to identify which modules are growing or declining in usage over time.
	measure 'Monthly Active Users by Module' =
			VAR _RefDate = [Reference Date]
			RETURN
			CALCULATE(
			    DISTINCTCOUNT('PostHog Application Usage Events'[User Identifier]),
			    DATESINPERIOD('Calendar'[Date], _RefDate, -30, DAY)
			)
		formatString: 0
		displayFolder: Module Activity
		lineageTag: 925f2e63-f2e5-411e-9a64-dae7655d333e

	/// Description:
	/// Calculates the total number of CRM activity events recorded within the selected date range and filter context. Unlike Active Users which counts unique users, Total Events measures the overall volume of interactions — reflecting how intensively the CRM is being used rather than how broadly. Use this measure to identify the most actively used services and modules by interaction volume.
	/// Business Logic:
	/// Applies SUM on Event Count column from PostHog Application Usage Events. Each row contains a pre-aggregated daily event count per unique user per module. Reacts to all filter context including date, platform, country, CRM service, module, instance, and user role filters.
	/// Usage:
	/// Use in bar charts alongside Active Users charts to provide a dual perspective on CRM engagement — breadth (users) versus depth (events). A service or module with high Total Events but low Active Users indicates intensive use by a small group of power users. A service with high Active Users but low Total Events suggests broad but shallow engagement — a potential target for training to increase depth of use.
	measure 'Total Events' =
			
			SUM('PostHog Application Usage Events'[Event Count])
		formatString: 0
		displayFolder: CRM Analytics
		lineageTag: 61d17616-ff0a-4579-a055-e82b9dff28b2

	/// Description:
	/// Returns a dynamic period label that automatically adapts to the currently selected metric in the Metric Selector slicer. Shows yesterday's date for DAU and DAU/MAU selections, the last 7 days for WAU, and the last 30 days for MAU. Falls back to the selected date slicer period when no metric is selected. Use as a universal dynamic subtitle across all metric-driven visuals on the Overview dashboard.
	/// Business Logic:
	/// Evaluates the selected value from the Metric Selector field parameter and returns the corresponding period label measure. DAU and Stickiness (DAU/MAU) share the same daily period label since both are based on yesterday's data. Falls back to Subtitle Period when no metric context is available.
	/// Usage:
	/// Apply via conditional formatting on visual subtitle using Field value → Dynamic Period Label. Use on the Top Countries chart, DAU trend chart, and any other visual that changes based on the Metric Selector. Eliminates the need for multiple static period labels across the Overview dashboard.
	measure 'Dynamic Period Label' =
			VAR _RefDate =
			    CALCULATE ( [Reference Date], REMOVEFILTERS ( 'PostHog Application Usage Events' ) )
			VAR _Yesterday = FORMAT ( _RefDate, "DD.MM.YYYY" )
			VAR _WAUStart = FORMAT ( _RefDate - 6, "DD.MM.YYYY" )
			VAR _MAUStart = FORMAT ( _RefDate - 29, "DD.MM.YYYY" )
			VAR _SelectedField =
			    CALCULATE ( MAX ( 'Metric Selector'[Field] ), ALLSELECTED ( 'Metric Selector' ) )
			RETURN
			SWITCH (
			    _SelectedField,
			    "DAU", "Yesterday: " & _Yesterday,
			    "WAU", "Last 7 days: " & _WAUStart & " – " & _Yesterday,
			    "MAU", "Last 30 days: " & _MAUStart & " – " & _Yesterday,
			    "DAU/MAU", "Yesterday: " & _Yesterday,
			    [Subtitle Period]
			)
		displayFolder: Report Helpers
		lineageTag: 65b5aa64-6219-4f50-bea6-d1737f07bf77

	/// Description:
	/// Generates a dynamic chart title based on the currently selected dimension and metric in the report slicers. Combines the selected breakdown dimension (Country, Instance, Platform, Operating System) with the selected metric (DAU, WAU, MAU, DAU/MAU) to produce titles such as Top Countries by DAU or Top Instances by WAU. Use this measure as a dynamic title on adoption visuals via conditional formatting.
	/// Business Logic:
	/// Reads the Order value from Dimension Selector and Metric Selector using SELECTEDVALUE to avoid composite key errors. Maps numeric order values to human-readable dimension and metric names. Returns Top Dimensions by Active Users as fallback when no selection is made.
	/// Usage:
	/// Apply via conditional formatting on visual title using Field value → Report Visual Title. Use on all visuals that change based on Dimension Selector and Metric Selector slicers on the Overview dashboard.
	measure 'Report Visual Title' =
			
			VAR _Dimension =
			    SELECTEDVALUE ( 'Dimension Selector'[Order] )
			
			VAR _Metric =
			    SELECTEDVALUE ( 'Metric Selector'[Order] )
			
			VAR _DimensionTitle =
			    SWITCH (
			        _Dimension,
			        0, "Countries",
			        1, "Instances",
			        2, "Platforms",
			        3, "Operating Systems",
			        "Dimensions"
			    )
			
			VAR _MetricTitle =
			    SWITCH(
			        _Metric,
			        0, "DAU",
			        1, "WAU",
			        2, "MAU",
			        3, "DAU/MAU",
			        "Active Users"
			    )
			
			RETURN
			"Top " & _DimensionTitle & " by " & _MetricTitle
		displayFolder: Report Helpers
		lineageTag: 87516198-a5b4-42db-bb95-a6cd964c58c5

	/// Description:
	/// Returns the most recent data refresh timestamp from the Data Refresh Status table. Indicates when the semantic model data was last updated. Use this measure in report visuals to display data freshness information to end users.
	/// Business Logic:
	/// Applies MAX on Last Refresh Date column from Data Refresh Status table. Returns the latest available refresh timestamp as a scalar value for use in card visuals and dynamic labels.
	/// Usage:
	/// Use as a KPI card or in report header to show users when the data was last refreshed. Combine with Next Refresh Date to communicate both last and upcoming refresh times.
	measure 'Last Data Refresh' = max('Data Refresh Status'[Last Refresh Date])
		displayFolder: Report Helpers
		lineageTag: 4116b962-d185-4804-a8c8-483e29975db5

	/// Description:
	/// Returns a formatted text string displaying the last data refresh timestamp for use in report headers and titles. Combines a static label with the Last Data Refresh measure to produce a human-readable data freshness indicator such as Report last update: 12/06/2026 18:45. Use this measure as a dynamic subtitle on report pages to inform users about data currency.
	/// Business Logic:
	/// Concatenates a static prefix Report last update: with the Last Data Refresh measure value. Inherits the timestamp from the Data Refresh Status table via the Last Data Refresh measure.
	/// Usage:
	/// Apply via conditional formatting on report page title or subtitle using Field value → Data Refresh Label. Use consistently across all report pages to display data freshness in the same format.
	measure 'Data Refresh Label' = "Report last update :" & " " &  [Last Data Refresh]
		displayFolder: Report Helpers
		lineageTag: 586f7dec-be62-43e7-9f16-bb65d0fcf913

	/// Description:
	/// 
	/// Counts the total number of Power BI report viewing sessions within the selected date range and filter context. Each session represents one report opening by a user. Use this measure as the primary metric for Power BI report adoption and engagement analysis.
	/// Business Logic:
	/// 
	/// Applies SUM on Session Count from PostHog Power BI Usage Events. Each row contains a pre-aggregated daily session count per user per report. Reacts to all filter context including date, instance, country, platform, and report filters.
	/// Usage:
	/// 
	/// Use as the primary KPI for Power BI report adoption. Compare across reports to identify most and least visited dashboards. Track trends over time to monitor report engagement growth.
	measure 'Total Report Sessions' =
			
			SUM('PostHog Power BI Usage Events'[Session Count])
		formatString: 0
		displayFolder: Power BI Analytics
		lineageTag: 68201b48-75d7-4e18-8c13-008e39067cea

	/// Description:
	/// 
	/// Counts the number of unique users who accessed at least one Power BI report within the selected date range and filter context. Use this measure to monitor how many users are actively engaging with embedded Power BI reports across client instances.
	/// Business Logic:
	/// 
	/// Applies DISTINCTCOUNT on User Identifier from PostHog Power BI Usage Events. Uses User Identifier for maximum coverage across all identification methods. Reacts to all filter context.
	/// Usage:
	/// 
	/// Use as a KPI card to monitor Power BI report user adoption. Compare with CRM Active Users to understand what share of CRM users also engage with Power BI reports.
	measure 'Active Report Users' =
			
			DISTINCTCOUNT('PostHog Power BI Usage Events'[User Identifier])
		formatString: 0
		displayFolder: Power BI Analytics
		lineageTag: 3d022e44-4075-4b82-a64a-db7fe64e1da7

	/// Description:
	/// 
	/// Counts the total number of user interaction events within Power BI report sessions. Reflects how deeply users engage with reports beyond simply opening them — including filter changes, page navigation, and visual interactions. Use alongside Total Report Sessions to measure engagement depth.
	/// Business Logic:
	/// 
	/// Applies SUM on Event Count from PostHog Power BI Usage Events. Multiple events can occur within a single session. A high ratio of Events to Sessions indicates deep report engagement.
	/// Usage:
	/// 
	/// Use alongside Total Report Sessions to calculate engagement depth. A report with high Sessions but low Events may indicate users open but do not interact — a signal for content improvement or training.
	measure 'Total Report Events' =
			
			SUM('PostHog Power BI Usage Events'[Event Count])
		formatString: 0
		displayFolder: Power BI Analytics
		lineageTag: 5201d509-84b4-4c4c-b041-3e8fbacec46e

	/// Description:
	/// 
	/// Measures the average number of user interactions per Power BI report session. A higher value indicates users are actively engaging with report content — filtering, navigating pages, or interacting with visuals. Use this measure to identify which reports drive the deepest user engagement.
	/// Business Logic:
	/// 
	/// Divides Total Report Events by Total Report Sessions using safe division with 0 as fallback. Reflects engagement depth per visit rather than visit frequency.
	/// Usage:
	/// 
	/// Use alongside Total Report Sessions to distinguish between popular reports (high sessions) and engaging reports (high events per session). Low values may indicate reports need better interactivity or content relevance.
	measure 'Avg Events per Session' =
			
			DIVIDE(
			    [Total Report Events],
			    [Total Report Sessions],
			    0
			)
		displayFolder: Power BI Analytics
		lineageTag: 056f5942-e6a0-42c8-baac-6a7043c33984

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Description:
	/// 
	/// Returns a dynamic page title showing the currently selected CRM service name for use on drill-through pages. Displays Users in: followed by the service name when a specific service is selected via drill-through. Returns Users in: All Services as fallback when no service is selected.
	measure 'Selected Service Title' = ```
			
			"Users in: " & 
			SELECTEDVALUE(
			    'PostHog Application Usage Events'[CRM Service Name],
			    "All Services"
			)
			```
		displayFolder: Report Helpers
		lineageTag: 6b3688e2-09d9-4368-b1f4-27b806594af6

	/// Counts the number of unique users who generated at least one CRM activity event on the day that corresponds to exactly one week before yesterday. Used as the baseline for week-over-week DAU comparison. Always reflects a fixed point in time regardless of date slicer selection.
	measure 'DAU Previous Week' =
			VAR _RefDate = [Reference Date]
			RETURN
			CALCULATE(
			    DISTINCTCOUNT('PostHog Application Usage Events'[User Identifier]),
			    DATESINPERIOD('Calendar'[Date], _RefDate - 7, -1, DAY)
			)
		formatString: #,##0
		displayFolder: WoW Comparison
		lineageTag: 9e8e9759-4d7a-42c1-808e-c7e942d1e9c4

	/// Shows the absolute change in Daily Active Users compared to the same day last week. A positive value indicates user growth; a negative value indicates a decline. Use alongside DAU WoW Change % to communicate week-over-week performance on the Overview dashboard.
	measure 'DAU WoW Change' = [Daily Active Users] - [DAU Previous Week]
		formatString: +#,##0;-#,##0;0
		displayFolder: WoW Comparison
		lineageTag: 930e4f1d-1ca4-4747-ade6-e240ed137521

	/// Shows the percentage change in Daily Active Users compared to the same day last week. Positive values indicate growth; negative values indicate decline. Use on the Overview dashboard DAU KPI card to provide immediate context on whether daily user activity is trending up or down.
	measure 'DAU WoW Change %' = DIVIDE( [DAU WoW Change], [DAU Previous Week], 0 )
		formatString: +0.0%;-0.0%;0%
		displayFolder: WoW Comparison
		lineageTag: 1adf517f-4f1d-4f61-b81f-4849cd72958c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Counts the number of unique users who generated at least one CRM activity event during the 7-day period ending one week before yesterday. Used as the baseline for week-over-week WAU comparison on the Overview dashboard.
	measure 'WAU Previous Week' =
			VAR _RefDate = [Reference Date]
			RETURN
			CALCULATE(
			    DISTINCTCOUNT('PostHog Application Usage Events'[User Identifier]),
			    DATESINPERIOD('Calendar'[Date], _RefDate - 7, -7, DAY)
			)
		formatString: #,##0
		displayFolder: WoW Comparison
		lineageTag: d6565533-7c96-4cfc-914d-c94fd3d6a9c0

	/// Shows the absolute change in Weekly Active Users compared to the equivalent 7-day period one week earlier. A positive value indicates user growth; a negative value indicates a decline in weekly engagement.
	measure 'WAU WoW Change' = [Weekly Active Users] - [WAU Previous Week]
		formatString: +#,##0;-#,##0;0
		displayFolder: WoW Comparison
		lineageTag: d290e14b-a0b0-4ebb-a95a-d466bd35464a

	/// Shows the percentage change in Weekly Active Users compared to the equivalent 7-day period one week earlier. Use on the Overview dashboard WAU KPI card to provide immediate context on whether weekly engagement is trending up or down.
	measure 'WAU WoW Change %' = DIVIDE( [WAU WoW Change], [WAU Previous Week], 0 )
		formatString: +0.0%;-0.0%;0%
		displayFolder: WoW Comparison
		lineageTag: ef209665-e4f8-4fea-b9d2-0e12c764e9da

	/// Counts the number of unique users who generated at least one CRM activity event during the 30-day period ending 31 days before yesterday. Used as the baseline for month-over-month MAU comparison on the Overview dashboard.
	measure 'MAU Previous Period' =
			VAR _RefDate = [Reference Date]
			RETURN
			CALCULATE(
			    DISTINCTCOUNT('PostHog Application Usage Events'[User Identifier]),
			    DATESINPERIOD('Calendar'[Date], _RefDate - 30, -30, DAY)
			)
		formatString: #,##0
		displayFolder: WoW Comparison
		lineageTag: b9a2e327-c432-4766-a01a-9e8e663b8eb2

	/// Shows the absolute change in Monthly Active Users compared to the equivalent 30-day period one month earlier. A positive value indicates user base growth; a negative value indicates a decline in monthly engagement.
	measure 'MAU MoM Change' = [Monthly Active Users] - [MAU Previous Period]
		formatString: +#,##0;-#,##0;0
		displayFolder: WoW Comparison
		lineageTag: 2d20d621-1ae9-426f-aa4e-919e1e344870

	/// Shows the percentage change in Monthly Active Users compared to the equivalent 30-day period one month earlier. Use on the Overview dashboard MAU KPI card to communicate monthly engagement trends at a glance.
	measure 'MAU MoM Change %' = DIVIDE( [MAU MoM Change], [MAU Previous Period], 0 )
		formatString: +0.0%;-0.0%;0%
		displayFolder: WoW Comparison
		lineageTag: a80c4d46-777c-4456-8673-841447ad5902

	/// Stickiness ratio (WAU/MAU) for the previous week window, used as Target in Zebra BI KPI card
	measure 'Stickiness Previous Week' = DIVIDE([WAU Previous Week], [MAU Previous Week], 0)
		formatString: 0.0%
		displayFolder: WoW Comparison
		lineageTag: 50e9a62e-b14b-4b4c-9a80-4887f4501b01

	measure 'Active Users Previous Period' = ```
			
			VAR PeriodLength = 
			    DATEDIFF(MIN(Calendar[Date]), MAX(Calendar[Date]), DAY) + 1
			RETURN
			    IF(
			        PeriodLength <= 30,
			        CALCULATE(
			            [Active Users],
			            DATEADD(Calendar[Date], -PeriodLength, DAY)
			        ),
			        BLANK()
			    )
			```
		formatString: 0
		displayFolder: CRM Analytics
		lineageTag: d8312ee7-bd5e-4ecf-9d5f-aaa042e9e4a5

	measure 'Active Services Previous Period' = ```
			
			VAR PeriodLength = 
			    DATEDIFF(MIN(Calendar[Date]), MAX(Calendar[Date]), DAY) + 1
			RETURN
			    IF(
			        PeriodLength <= 30,
			        CALCULATE(
			            [Active Services],
			            DATEADD(Calendar[Date], -PeriodLength, DAY)
			        ),
			        BLANK()
			    )
			```
		formatString: 0
		displayFolder: CRM Analytics
		lineageTag: 961a8ffb-2d58-49a3-a6a1-8d0189dce663

	measure 'Active Modules Previous Period' = ```
			
			VAR PeriodLength = 
			    DATEDIFF(MIN(Calendar[Date]), MAX(Calendar[Date]), DAY) + 1
			RETURN
			    IF(
			        PeriodLength <= 30,
			        CALCULATE(
			            [Active Modules],
			            DATEADD(Calendar[Date], -PeriodLength, DAY)
			        ),
			        BLANK()
			    )
			```
		formatString: 0
		displayFolder: CRM Analytics
		lineageTag: cdd26f24-5e5e-4889-b7ae-c12cbce066eb

	measure 'Avg Events Previous Period' = ```
			
			VAR PeriodLength = 
			    DATEDIFF(MIN(Calendar[Date]), MAX(Calendar[Date]), DAY) + 1
			RETURN
			    IF(
			        PeriodLength <= 30,
			        CALCULATE(
			            [Avg Events per User],
			            DATEADD(Calendar[Date], -PeriodLength, DAY)
			        ),
			        BLANK()
			    )
			```
		displayFolder: CRM Analytics
		lineageTag: 9c699533-b282-47b6-a110-1ce9585c6ab1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MAU Previous Week' =
			VAR _RefDate = [Reference Date]
			RETURN
			CALCULATE(
			    DISTINCTCOUNT('PostHog Application Usage Events'[User Identifier]),
			    DATESINPERIOD('Calendar'[Date], _RefDate - 7, -30, DAY)
			)
		formatString: 0
		displayFolder: WoW Comparison
		lineageTag: 7b9f5d0b-be0b-4151-a5d6-9ede9c3d0bea

	measure 'Weekly Active Users (Calendar)' =
			
			CALCULATE (
			    DISTINCTCOUNT ( 'PostHog Application Usage Events'[User Identifier] ),
			    ALLEXCEPT ( 'Calendar', 'Calendar'[Week] )
			)
		formatString: 0
		displayFolder: WoW Comparison
		lineageTag: c6b9dc45-0820-4320-a923-1078e27f1fc8

	measure 'Weekly Active Users (Calendar) Previous Week' =
			
			VAR _CurrentWeek = MAX ( 'Calendar'[Week] )
			RETURN
			    CALCULATE (
			        [Weekly Active Users (Calendar)],
			        ALL ( 'Calendar' ),
			        'Calendar'[Week] = _CurrentWeek - 7
			    )
		formatString: 0
		displayFolder: WoW Comparison
		lineageTag: 95260ab5-b249-4a8f-8444-e87bd4030f55

	measure 'Reference Date' = MAX ( 'Calendar'[Date] )
		isHidden
		displayFolder: Report Helpers
		lineageTag: 7126a8db-7c4c-4796-bb8d-fc309feda5e4

	measure 'Listed Rows' = ```
			COUNTROWS(
			    SUMMARIZE(
			        'PostHog Application Usage Events',
			        
			        'PostHog Application Usage Events'[User Email]
			        
			    )
			)
			```
		formatString: 0
		displayFolder: Report Helpers
		lineageTag: 25a033c8-9187-40e7-b66a-5b5e8befb12b

	column Value
		isHidden
		formatString: 0
		lineageTag: 94df9b24-7ec3-4148-b5c1-b93df9e29a37
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Value]

		annotation SummarizationSetBy = Automatic

	partition _Measures = calculated
		mode: import
		source = Row("Value", BLANK())

	annotation PBI_Id = c43a2bd4a4314356bc1430eb399f725f

	annotation 436ba87b-9c83-4389-a31b-ebd06a36be98 = {"Expression":""}

