/// Records Power BI embedded report usage events collected from PostHog across all CRM client instances. Each row represents a unique combination of user, date, and report, containing both the number of sessions and the number of events generated within those sessions. Used for Power BI adoption analysis, report engagement tracking, and embedded dashboard usage monitoring across client deployments.
table 'PostHog Power BI Usage Events'
	lineageTag: 3241599c-9426-4301-9c7f-d2aedfcd587e

	column 'Event Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: d97ad1d0-e71d-4286-9044-a3d9ed9f60d8
		summarizeBy: none
		sourceColumn: Event Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'CRM Instance Name'
		dataType: string
		lineageTag: 7be32ae3-2fd5-4266-bcad-aa6ebb865190
		summarizeBy: none
		sourceColumn: CRM Instance Name

		annotation SummarizationSetBy = Automatic

	column 'User ID'
		dataType: string
		lineageTag: 7d9af54b-13dc-4a65-a3f4-8790babb647f
		summarizeBy: none
		sourceColumn: User ID

		annotation SummarizationSetBy = Automatic

	column 'User Identifier'
		dataType: string
		lineageTag: 1763e1a6-a034-4a2d-9f06-b69196ba084c
		summarizeBy: none
		sourceColumn: User Identifier

		annotation SummarizationSetBy = Automatic

	column 'User Email'
		dataType: string
		lineageTag: 02da984e-4367-4156-a376-65ebfbc25a65
		summarizeBy: none
		sourceColumn: User Email

		annotation SummarizationSetBy = Automatic

	column 'User Role'
		dataType: string
		lineageTag: 67471979-cf07-4c51-8665-c5c9bceacbd0
		summarizeBy: none
		sourceColumn: User Role

		annotation SummarizationSetBy = Automatic

	column Platform
		dataType: string
		lineageTag: 88f9c0af-cd60-4ae7-b271-846df290bcc4
		summarizeBy: none
		sourceColumn: Platform

		annotation SummarizationSetBy = Automatic

	column 'Operating System'
		dataType: string
		lineageTag: c8a36479-36de-428f-ab4e-1e36d457158f
		summarizeBy: none
		sourceColumn: Operating System

		annotation SummarizationSetBy = Automatic

	column 'Device Model'
		dataType: string
		lineageTag: bd228bc9-7521-4a73-917f-32138b5cff23
		summarizeBy: none
		sourceColumn: Device Model

		annotation SummarizationSetBy = Automatic

	column 'CRM Service Name'
		dataType: string
		lineageTag: f39b446e-09fb-4f81-a3fe-65363c8c5e15
		summarizeBy: none
		sourceColumn: CRM Service Name

		annotation SummarizationSetBy = Automatic

	/// Description
	/// The unique numeric identifier of the Power BI embedded report accessed by the user. Used as the relationship key between PostHog Power BI Usage Events and Power BI Report Mapping table. Enables enrichment of usage events with report name and client instance information. Hidden from reports — use Report Name from Power BI Report Mapping for display purposes.
	/// 
	/// Business Logic
	/// Each value corresponds to a specific Power BI embedded report as defined in the Power BI Report Mapping table. The relationship is many-to-one — multiple usage events may reference the same report ID. Use this field to join Power BI usage data with report metadata for analysis by report name or client instance.
	/// 
	/// Usage
	/// Do not use this column directly in report visuals — it is a technical relationship key. Use Report Name from Power BI Report Mapping instead for all display and filtering purposes. Required for the relationship between PostHog Power BI Usage Events and Power BI Report Mapping to function correctly.
	column 'Report ID'
		dataType: int64
		formatString: 0
		displayFolder: Event Info
		lineageTag: 17c13515-893a-48e6-af23-215efb01434b
		summarizeBy: count
		sourceColumn: Report ID

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: 67711058-3125-42a0-850e-2aab8f12e7f5
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 730a8e9b-ce12-4904-ab92-c47ba8979353
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column 'Application Version'
		dataType: string
		lineageTag: 9331628c-cd34-45b0-94cf-9fef1df71db8
		summarizeBy: none
		sourceColumn: Application Version

		annotation SummarizationSetBy = Automatic

	/// Description
	/// The number of times a user opened or accessed the Power BI embedded report within a single calendar day. Each session represents one report viewing instance. Multiple events may occur within a single session. Use SUM of this column in DAX measures to calculate total report visit volume. Do not aggregate directly in visuals without a predefined measure.
	/// 
	/// Business Logic
	/// Each row contains a pre-aggregated daily count of sessions per unique user per report. A session begins when a user opens the Power BI report and may contain multiple interaction events. Use alongside Event Count to distinguish between visit frequency (Session Count) and engagement depth (Event Count) — a high Session Count with low Event Count may indicate users open the report but do not interact deeply.
	/// 
	/// Usage
	/// Use in DAX measures to calculate total Power BI report visit volume. Combine with Event Count to analyze the ratio of sessions to interactions. Compare across reports, instances, and time periods to monitor report adoption trends and identify underutilized embedded reports.
	column 'Session Count'
		dataType: int64
		displayFolder: Event Info
		lineageTag: fe077642-ed4b-4bd8-bdb9-50368cfce01f
		summarizeBy: sum
		sourceColumn: Session Count

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Description
	/// The total number of individual user interaction events recorded within Power BI report sessions for a given user, date, and report combination. One session may contain multiple events such as filter changes, page navigation, or visual interactions. Use SUM of this column in DAX measures to calculate total interaction volume. Do not aggregate directly in visuals without a predefined measure.
	/// 
	/// Business Logic
	/// Each row contains a pre-aggregated daily count of events per unique user per report. A single session may generate multiple events. Use alongside Session Count to understand both visit frequency and interaction depth — high Event Count with low Session Count indicates deep engagement per session.
	/// 
	/// Usage
	/// Use in DAX measures to calculate total Power BI report interaction volume. Combine with Session Count to analyze engagement depth. Compare across reports, instances, and user roles to identify which reports drive the most user interaction.
	column 'Event Count'
		dataType: int64
		displayFolder: Event Info
		lineageTag: f665f906-48bc-4dc4-8a36-86de9c925bbf
		summarizeBy: sum
		sourceColumn: Event Count

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Instance Report Key'
		dataType: string
		lineageTag: 3f38f750-dd4f-49b9-9277-a399c1edf755
		summarizeBy: none
		sourceColumn: Instance Report Key

		annotation SummarizationSetBy = Automatic

	partition 'PostHog Power BI Usage Events' = m
		mode: import
		source =
				let
				    Source = AzureStorage.Blobs("https://pbecrmde.blob.core.windows.net/crm/"),
				    #"Imported File" = Source{[
				        #"Folder Path" = "https://pbecrmde.blob.core.windows.net/crm/",
				        Name = "243719954656925104/uua_power_bi_usage_daily.csv"
				    ]}[Content],
				    #"Imported CSV" = Csv.Document(
				        #"Imported File",
				        [Delimiter=";", Encoding=65001, QuoteStyle=QuoteStyle.None]
				    ),
				    #"Promoted Headers" = Table.PromoteHeaders(
				        #"Imported CSV",
				        [PromoteAllScalars=true]
				    ),
				    #"Renamed Columns" = Table.RenameColumns(
				        #"Promoted Headers",
				        {
				            {"event_count", "Event Count"},
				            {"session_count", "Session Count"},
				            {"report_id", "Report ID"},
				            {"app_version", "Application Version"},
				            {"city", "City"},
				            {"country", "Country"},
				            {"device_model", "Device Model"},
				            {"event_date", "Event Date"},
				            {"instance", "CRM Instance Name"},
				            {"os", "Operating System"},
				            {"platform", "Platform"},
				            {"role_name", "User Role"},
				            {"service", "CRM Service Name"},
				            {"user_email", "User Email"},
				            {"user_id", "User ID"},
				            {"user_key", "User Identifier"}
				        }
				    ),
				    #"Changed Type" = Table.TransformColumnTypes(
				        #"Renamed Columns",
				        {
				            {"Report ID", Int64.Type},
				            {"Event Date", type date},
				            {"Event Count", Int64.Type},
				            {"Session Count", Int64.Type}
				        }
				    ),
				    #"Replaced Value" = Table.ReplaceValue(
				        #"Changed Type",
				        ".pharmahrm.com",
				        "",
				        Replacer.ReplaceText,
				        {"CRM Instance Name"}
				    ),
				    #"Added Instance Report Key" = Table.AddColumn(
				        #"Replaced Value",
				        "Instance Report Key",
				        each [CRM Instance Name] & "_" & Text.From([Report ID])
				    ),
				    // Відсікання неповного дня (UTC) — event_date рахується в UTC у ClickHouse
				    #"Filtered Incomplete Day" = Table.SelectRows(
				        #"Added Instance Report Key",
				        each [Event Date] < DateTime.Date(DateTimeZone.RemoveZone(DateTimeZone.FixedUtcNow()))
				    ),
				    #"Sorted Rows" = Table.Sort(#"Filtered Incomplete Day",{{"Event Date", Order.Descending}}),
				    #"Filtered Rows" = Table.SelectRows(#"Sorted Rows", each true),
				#"Overridden User Identifier" = Table.RemoveColumns(#"Filtered Incomplete Day", {"User Identifier"}),
				#"Added User Identifier" = Table.RenameColumns(
				    Table.DuplicateColumn(#"Overridden User Identifier", "User Email", "User Identifier"),
				    {}
				),
				    #"Sorted Rows1" = Table.Sort(#"Added User Identifier",{{"Event Date", Order.Descending}})
				in
				    #"Sorted Rows1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

