/// Stores the data refresh timestamp for the semantic model. Used to display the last data update time and next scheduled refresh in reports. Helps users understand the freshness of the data they are viewing.
table 'Data Refresh Status'
	lineageTag: 76f6b950-9c3f-44f6-8bc2-975e963ad2b2

	/// Technical source column generated by Power Query at refresh time. Used as the base for calculating Last Refresh Date and Next Refresh Date. Hidden from reports.
	column GetCurrentDateTime
		dataType: dateTime
		isHidden
		formatString: General Date
		lineageTag: 934a8e97-8b47-4c5a-9022-15a5c741f5e5
		summarizeBy: none
		sourceColumn: GetCurrentDateTime

		variation Variation
			isDefault
			relationship: 629e52e1-00a1-455d-94b5-c579a4f0f18d
			defaultHierarchy: LocalDateTable_a84b3409-4c6e-47a4-a2ff-e8b6f2726615.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// The date and time when the semantic model was last successfully refreshed, formatted as dd/mm/yyyy hh:mm. Display in reports to inform users about data currency.
	column 'Last Refresh Date' = FORMAT(VALUES('Data Refresh Status'[GetCurrentDateTime]),"dd/mm/yyyy hh:mm")
		dataType: dateTime
		formatString: General Date
		lineageTag: 41770886-665f-45fd-b9ca-47e8fea1ef05
		summarizeBy: none

		variation Variation
			isDefault
			relationship: 65cdcc73-e7d2-4b6e-9c6f-91d41b836eef
			defaultHierarchy: LocalDateTable_73cbcdb8-60a9-4faa-92fb-beb286760bad.'Date Hierarchy'

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	/// The estimated date and time of the next scheduled data refresh, calculated as one hour after the last refresh. Displayed in reports to help users anticipate data availability.
	column 'Next Refresh Date' = FORMAT(VALUES('Data Refresh Status'[Last Refresh Date])+TIME(1,0,0),"dd/mm/yyyy hh:mm")
		dataType: dateTime
		formatString: General Date
		lineageTag: 6a2d71a1-ded2-4781-ab15-1346fd04e13e
		summarizeBy: none

		variation Variation
			isDefault
			relationship: c1e0b318-fa69-4a93-bff3-ac933c8d7e8b
			defaultHierarchy: LocalDateTable_d0d47e85-ce06-469c-b3c6-210fab3eb9db.'Date Hierarchy'

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	partition 'Data Refresh Status' = m
		mode: import
		source =
				let
				    Источник = GetCurrentDateTime(2),
				    #"Преобразовано в таблицу" = #table(1, {{Источник}}),
				    #"Вызвана настраиваемая функция" = Table.AddColumn(#"Преобразовано в таблицу", "GetCurrentDateTime", each GetCurrentDateTime(2)),
				    #"Удаленные столбцы" = Table.RemoveColumns(#"Вызвана настраиваемая функция",{"Column1"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Удаленные столбцы",{{"GetCurrentDateTime", type datetime}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

