/// Contains deployment records for the web CRM application built on Flutter. Each row represents a specific application version deployed to a CRM instance. Used to enrich PostHog web events with the correct application version when it is not available directly from the event.
table 'Web App Deployments'
	lineageTag: d699b0cb-fc41-4cc1-80e4-6ae52d252a29

	/// The unique identifier (slug) of the client CRM instance. Used as the relationship key between Web App Deployments and PostHog Application Usage Events. Each value represents a separate client deployment.
	column 'CRM Instance Name'
		dataType: string
		isHidden
		lineageTag: 02ee794e-658b-4110-8f76-a9c2a60abf5e
		summarizeBy: none
		sourceColumn: CRM Instance Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Technical identifier of the web application framework. Always Flutter.Web for all records. Hidden from reports as it provides no analytical value.
	column 'Application Title'
		dataType: string
		isHidden
		lineageTag: 293afbdd-770e-4ede-9a58-0f5d53804f9a
		summarizeBy: none
		sourceColumn: Application Title

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// The version of the Flutter web application deployed to the client instance. Used to enrich PostHog web events with the correct application version via the CRM Instance Name relationship.
	column 'Application Version'
		dataType: string
		displayFolder: Deployment Info
		lineageTag: 6c81c98a-c4a0-4475-a947-443d1e26f6e8
		summarizeBy: none
		sourceColumn: Application Version

		annotation SummarizationSetBy = Automatic

	/// The date and time when the current application version was last deployed to the client instance. Use this field to identify recently updated instances or monitor deployment rollout progress.
	column 'Latest Deployment Date'
		dataType: dateTime
		formatString: General Date
		displayFolder: Deployment Info
		lineageTag: 5e74a403-6add-43ad-9fe5-e3aa8804a6e6
		summarizeBy: none
		sourceColumn: Latest Deployment Date

		variation Variation
			isDefault
			relationship: eb5f5d29-f021-45f3-80c8-23282c23bd33
			defaultHierarchy: LocalDateTable_cf2b5915-6af8-4cf7-9b9e-55e1beed0726.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	partition 'Web App Deployments' = m
		mode: import
		source =
				let
				    Source = AzureStorage.Blobs("https://pbecrmde.blob.core.windows.net/crm/"),
				    #"https://pbecrmde blob core windows net/crm/_243719954656925104/ts_customer csv" = Source{[#"Folder Path"="https://pbecrmde.blob.core.windows.net/crm/",Name="243719954656925104/ts_customer.csv"]}[Content],
				    #"Imported CSV" = Csv.Document(#"https://pbecrmde blob core windows net/crm/_243719954656925104/ts_customer csv",[Delimiter=";", Columns=23, Encoding=1251, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Imported CSV", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"company_id", Int64.Type}, {"instance_name", type text}, {"crm_web_url", type text}, {"zitadel_org_id", type text}, {"status", type text}, {"instance_ip", type text}, {"is_prod", type text}, {"aws_account_admin_email", type text}, {"aws_account_id", Int64.Type}, {"aws_customer_id", Int64.Type}, {"product_code", type text}, {"aws_instance_status", type text}, {"license_package_id", Int64.Type}, {"number_of_license", Int64.Type}, {"package_name", type text}, {"dimension", type text}, {"normalized_package_name", type text}, {"aws_license_number", Int64.Type}, {"expires_at", type datetime}, {"application_id", Int64.Type}, {"application_name", type text}, {"app_version", type text}, {"app_updated_at", type datetime}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type", each ([application_name] = "Flutter.Mobile" or [application_name] = "Flutter.Web" or [application_name] = "Platform")),
				    #"Removed Duplicates" = Table.Distinct(#"Filtered Rows", {"instance_name"}),
				    #"Filtered Rows1" = Table.SelectRows(#"Removed Duplicates", each true),
				    #"Removed Columns" = Table.RemoveColumns(#"Filtered Rows1",{"crm_web_url", "company_id", "status", "instance_ip", "is_prod", "aws_account_admin_email", "aws_account_id", "zitadel_org_id", "aws_instance_status", "product_code", "aws_customer_id", "license_package_id", "number_of_license", "package_name", "dimension", "normalized_package_name", "aws_license_number", "expires_at", "application_id"}),
				    #"Removed Duplicates1" = Table.Distinct(#"Removed Columns", {"instance_name"}),
				    #"Sorted Rows" = Table.Sort(#"Removed Duplicates1",{{"instance_name", Order.Ascending}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Sorted Rows",{{"app_updated_at", "Latest Deployment Date"}, {"app_version", "Application Version"}, {"application_name", "Application Title"}, {"instance_name", "CRM Instance Name"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

